name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: | 
      	swift build -v "$arg1 $arg2"
      env:
      - arg1='-sdk `xcrun --sdk iphonesimulator --show-sdk-path`'
      - arg2='-target x86_64-apple-ios13.0-simulator'
