name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        swift build -v \
          -sdk `xcrun --sdk iphonesimulator --show-sdk-path` \
          -target x86_64-apple-ios13.0-simulator
